-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "about_me" DROP NOT NULL,
ALTER COLUMN "magicToken" DROP NOT NULL,
ALTER COLUMN "magicTokenExpires" DROP NOT NULL,
ALTER COLUMN "sessionToken" DROP NOT NULL;
